services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=new_swe573_db
      - POSTGRES_USER=eray57
      - POSTGRES_PASSWORD=new_password
      - POSTGRES_HOST=db
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=new_swe573_db
      - POSTGRES_USER=eray57
      - POSTGRES_PASSWORD=new_password
    ports:
      - "1234:5432"