# Generated by Django 4.2.16 on 2024-12-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0002_alter_post_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('solved', 'Solved')], default='open', max_length=10, verbose_name='Status'),
        ),
    ]
