# Generated by Django 4.2.16 on 2024-12-03 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0003_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
