# Generated by Django 4.2.16 on 2024-12-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0004_remove_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('solved', 'Solved')], default='open', editable=False, max_length=10),
        ),
    ]
