# Generated by Django 4.2.16 on 2024-12-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0005_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='size',
        ),
        migrations.AddField(
            model_name='post',
            name='size_x',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Length (cm)'),
        ),
        migrations.AddField(
            model_name='post',
            name='size_y',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Width (cm)'),
        ),
        migrations.AddField(
            model_name='post',
            name='size_z',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Height (cm)'),
        ),
    ]
