# Generated by Django 4.2.16 on 2024-12-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0006_remove_post_size_post_size_x_post_size_y_post_size_z'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('brown', 'Brown'), ('pink', 'Pink'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('multicolor', 'Multicolor'), ('other', 'Other')], default='none', max_length=20, null=True, verbose_name='Color'),
        ),
    ]
