# Generated by Django 4.2.16 on 2024-12-04 12:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0007_alter_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('none', 'None'), ('black', 'Black'), ('white', 'White'), ('gray', 'Gray'), ('red', 'Red'), ('blue', 'Blue'), ('green', 'Green'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('brown', 'Brown'), ('pink', 'Pink'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('multicolor', 'Multicolor'), ('other', 'Other')], max_length=20), blank=True, default=list, null=True, size=None, verbose_name='Colors'),
        ),
    ]
