# Generated by Django 4.2.16 on 2024-12-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0008_alter_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.TextField(blank=True, default='[]', null=True, verbose_name='Colors'),
        ),
    ]
