# Generated by Django 4.2.16 on 2024-12-04 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0009_alter_post_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(blank=True, default='none', max_length=500, null=True, verbose_name='Colors'),
        ),
    ]
