# Generated by Django 4.2.16 on 2024-12-05 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('whatisthis', '0013_remove_comment_parent_comment_reply'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='whatisthis.reply'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='whatisthis.comment'),
        ),
    ]
